---
- name: Install golang package
  become: true
  apt:
    pkg: ["golang-go"]
    update_cache: true

- name: Add go folder to path
  when: ansible_env.PATH is not search('{{ansible_user_dir}}/go/bin')
  lineinfile:
    dest: "{{ansible_user_dir}}/.bashrc"
    line: "export PATH=$PATH:~/go/bin"
    owner: "{{ansible_user}}"