- hosts: all
  roles:
    - role: nmap
      when: install_nmap
    - role: masscan
      when: install_masscan
    - role: gau
      when: install_gau
    - role: dnsvalidator
      when: install_dnsvalidator
    - role: massdns
      when: install_massdns
    - role: puredns
      when: install_puredns
