---

- name: install pip3 and/or git
  become: true
  apt:
    pkg: ["python3-pip", "git"]
    update_cache: true

- name: clone dnsvalidator repo
  git:
    repo: https://github.com/vortexau/dnsvalidator.git
    dest: ~/dnsvalidator

- name: check if dnsvalidator is already installed
  command: which dnsvalidator
  changed_when: false
  failed_when: dnsvalidator_installed.rc not in [0,1]
  register: dnsvalidator_installed

- name: install from source
  become: true
  command:
    chdir: "{{ansible_user_dir}}/dnsvalidator"
    cmd: python3 setup.py install
  when: dnsvalidator_installed.rc not in [ 0 ]
